---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install base packages
  apt:
    name:
      - curl
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - conntrack
      - docker.io
      - acl
    state: present

- name: Add ubuntu user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes