---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install ACL and dependencies
  apt:
    name: [acl, curl, apt-transport-https, ca-certificates, software-properties-common, conntrack, docker.io]
    state: present

- name: Ensure group "docker" exists
  group:
    name: docker
    state: present

- name: Create ubuntu user (IMPORTANT)
  user:
    name: ubuntu
    shell: /bin/bash
    groups: docker
    append: yes
    create_home: yes

- name: Fix permissions for ubuntu home
  file:
    path: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    mode: '0755'
    state: directory
  when: not ansible_check_mode